### ISSUE TITLE
Use Fraola Inline Editor

### ISSUE THREAD

**Issue by rweas** [BootstrapCMS/CMS#116]
https://editor.froala.com/#inline-demo
Just click and edit what you see on that link.

It would be really cool if hitting edit page used fraola inline to do so, but it would be a good idea if it was optionally.

**Comment by GrahamCampbell** [comment]
I think this might be too restrictive for people, but I'm not too sure. This might be a good alternative to using markdown in the blog posts though. If you're up for sending a pull, I'll be able to review it with a few days or so.

**Comment by rweas** [comment]
Cool! I'll get to work on it.

**Comment by rweas** [comment]
I'll probably add a client setting to each user. If they're a client they'll get the fraola inline editor with no CSS or js so as not to confuse them. Otherwise things will stay the same. Except for blog posts I'll make them always fraola.

**Comment by GrahamCampbell** [comment]
NB, please do this on the master branch rather than 0.8. :)

**Comment by rweas** [comment]
OK no problem.

**Comment by rweas** [comment]
@GrahamCampbell I added the blog post editor. #118 
Using it for inline page editing is next on my list. I probably won't get to it in a while though.
