### ISSUE TITLE
Question re L4 -> L5 and Controller Namespace

### ISSUE THREAD

**Issue by londoh** [BootstrapCMS/CMS#121]
This is not an issue, more to do with my lack of understanding of L5 controller namespaces but I'm hoping you can help:

I have an existing L4 app and would like to bring it into L5 using BootstrapCMS as a basis and I'll use it as an example altho it may not be relevant to the more generic question

my app is entirely within its own folder so:
```
app/Myapp 
app/Myapp/Widgets 
app/Myapp/Controllers
```
etc its namespaced and works ok in L4

I've set psr4 autoload correctly in composer.json

in Http/Providers/RouteServiceProvider Graham Campbell sets a namespace so:

```php
class RouteServiceProvider extends ServiceProvider
{
    /** ...
     */
    protected $namespace = 'GrahamCampbell\BootstrapCMS\Http\Controllers';
```
I now set a basic route in Http/routes.php like this:
```php
Route::get('/', ['uses' => 'Myapp\Controllers\WidgetController@index']);
```
when I access that route I get this ReflectionException:

>Class GrahamCampbell\BootstrapCMS\Http\Controllers\Myapp\Controllers\WidgetController does not exist

I've read the L5 docs and matt stauffer's upgrade blog esp. controllers, namespaces and RouteServiceProvider 

But I dont see any override for location of Myapp controllers under these circumstances. In fact it seems I am now forced to place all my controllers under Http/Controllers.

Surely I am mistaken here? Do you know any way to leave my existing controllers in their existing location?

thanks

l.

**Comment by GrahamCampbell** [comment]
`Myapp\Controllers` should be `GrahamCampbell\BootstrapCMS\Http\Controllers`.

**Comment by londoh** [comment]
tnx for reply

as in move myapp\controllers\* to gc...controllers\ ?

**Comment by londoh** [comment]
Perhaps I'm still misunderstanding what Laravel 5 is doing in this respect. But as I'm seeing it, L5 now enforces a very fixed opinion about where controllers can live, rather than the flexible attitude from L4
>controllers may live anywhere on the file system, as long as composer knows how to load them

And that seems strange.

Anyway I know this isn't a BootstrapCms issue and I'm grateful for the space to ask the OT question. If you have any input I'm even more grateful, otherwise we can close the thread.

**Comment by GrahamCampbell** [comment]
> But as I'm seeing it, L5 now enforces a very fixed opinion about where controllers can live

No it doesn't. They can be anywhere you want.

**Comment by londoh** [comment]
thank you very much for reply

Obviously I posted here originally because I didnt know how to do that.

So altho I'm sure you must be correct, I still dont get it.

I think my original post explained my specific case and problem reasonably well, and I asked help for a solution. 

You very kindly gave one. I tried your solution and variations, but still cant see that it works in this case.

But thank you anyway

**Comment by GrahamCampbell** [comment]
You're probably getting confused by the route namespace wrapper that requires my route file.

**Comment by londoh** [comment]
well perhaps I am

I just looked again: once $namespace is set in RouteServiceProvider eg:
```php
protected $namespace = 'GrahamCampbell\BootstrapCMS\Http\Controllers';
```

laravel is then forcing any other controller or route namespace relative to that.

therefore my problem to "just" drop Myapp into BootstrapCMS

**Comment by londoh** [comment]
fwiw this L5 pull request fixes the problem, which I didnt describe well enough:
https://github.com/laravel/framework/pull/7859
