### ISSUE TITLE
Upgrade To Latest Laravel 5.0

### ISSUE THREAD

**Issue by GrahamCampbell** [BootstrapCMS/CMS#122]

**Comment by jallowmamadou** [comment]
exception 'PDOException' with message 'SQLSTATE[42S02]: Base table or view not found: 1146 Table 'cms_db.groups' doesn't exist' in /var/www/dev/lcms/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php:355
Stack trace:

i am trying to install your boostrapscms but there is no groups table migration. please help

**Comment by GrahamCampbell** [comment]
@jallowmamadou Have you actually read the readme. DO NOT RUN `php artisan migrate`. DO RUN `php artisan app:install`. This is also totally unrelated to this issue.

**Comment by GrahamCampbell** [comment]
And the upgrade to the latest version of laravel 5 is done.
