### ISSUE TITLE
Stuck while installing v0.9 (Laravel5) at step5

### ISSUE THREAD

**Issue by mrrtee** [BootstrapCMS/CMS#124]
I'm PHP developer but I'm new on Laravel development...

I do follow on installation guide from 1-4 without problem, but when I'm on step 5, I don't know where can I set 
- You can disable verification emails in config/packages/graham-campbell/navigation/config.php
- You must set the contact email in config/packages/graham-campbell/contact/config.php

Furthermore, I don't know how to setup HHVM on my local machine..? Can you help me ?

**Comment by mrrtee** [comment]
More information: when I try to login or register, it will show "Error 500, Internal Server Error"

**Comment by GrahamCampbell** [comment]
> I do follow on installation guide from 1-4 without problem, but when I'm on step 5, I don't know where can I set 

Oh sorry. I forgot to update the paths. Will do that now...

> More information: when I try to login or register, it will show "Error 500, Internal Server Error"

Go into config/app, and set debug to true.

**Comment by GrahamCampbell** [comment]
https://github.com/BootstrapCMS/CMS/commit/02ba2a15fccf9fb7a6e2c9ac74580a3f301adbe5 updates the config docs for you btw.

**Comment by mrrtee** [comment]
Thank you, Graham.. I will try

**Comment by goedda** [comment]
@mrrtee 

Try also to change the 'default' configuration in ROOT/config/cache.php to 'array'. This should allow you at least to start exploring Bootstrap-CMS. Once you are more familiar with Laravel and caching in Bootstrap-CMS, you may configure the caching correctly.
With the native cache settings, the login and the register, respectively, wont' work and throw an (caching) error.

@GrahamCampbell 

I wrote you an email (February, 8th, Subject:"Bootstrap-CMS, newbie issues"), which addresses this issue amongst others. I wrote an email, because I listed there several issues that are not actual issues, more like "newbie" problems that could be prevented with a few sentences in the read me file.

**Comment by GrahamCampbell** [comment]
> Try also to change the 'default' configuration in ROOT/config/cache.php to 'array'.

I think it is already set to array, or at least, it should be, let me check...

**Comment by GrahamCampbell** [comment]
Looks like I accidentally changed it during the L5 config updates I did. I've updated it ti match my docs.

**Comment by GrahamCampbell** [comment]
> With the native cache settings, the login and the register, respectively, won't work and throw an (caching) error.

Yep, we need a cache driver that supports cache tags. :)

**Comment by GrahamCampbell** [comment]
> I wrote you an email (February, 8th, Subject:"Bootstrap-CMS, newbie issues"), which addresses this issue amongst others.

Sorry, I did notice your email, but I haven't had a chance to respond yet.

**Comment by saif0909** [comment]
hey bro i got this error in login and register page 
call_user_func_array() expects parameter 1 to be a valid callback, class 'Illuminate\Cache\FileStore' does not have a method 'tags' 

any solution ?

**Comment by GrahamCampbell** [comment]
Yes. This is clearly documented. You are not allowed to use the file driver.

**Comment by GrahamCampbell** [comment]
> Bootstrap CMS provides caching functionality, and when enabled, requires a caching server. Note that caching will not work with Laravel's file or database cache drivers.

**Comment by elwolfy** [comment]
![image](https://cloud.githubusercontent.com/assets/5488394/10356383/3b251842-6d3c-11e5-855c-48a9872fa3d5.png)
![image](https://cloud.githubusercontent.com/assets/5488394/10356385/43da7aea-6d3c-11e5-8e3b-5bf3cc287c8e.png) I get an: No supported encrypter found. The cipher and / or key length are invalid.
Why is the cause?

**Comment by Mixpeal** [comment]
hello graham, pls can we chat, wanna discuss a biz with u

**Comment by Mixpeal** [comment]
and what cause the above screenshot

**Comment by GrahamCampbell** [comment]
> Why is the cause?

You need to sent an encryption key,

**Comment by arttsai** [comment]
> I get an: No supported encrypter found. The cipher and / or key length are invalid.
Why is the cause?

In you cms folder, run 'php artisan key:generate' and put that key generated in config/app.php, searching the keyword 'APP_KEY'.

That's all.
