### ISSUE TITLE
class NavigationSubscriber, weird constructor

### ISSUE THREAD

**Issue by goedda** [BootstrapCMS/CMS#127]
I am trying to add a menu item to the admin/bar BootstrapCMS menu. And I have been failing miserably so far, so here the question, could you provide an example and please do not reference 'factory.php' as a prime example as you did on git Laravel-Navigation...
Anyhow, while parsing your code, i.e. trying to find the reason for my failure, I noticed the constructor in the class NavigationSubscriber looking weird. Can you confirm or refute that it is ok, please? It may explain why I can't add any menu items.
Thanks.
https://github.com/BootstrapCMS/CMS/blob/master/app/Subscribers/NavigationSubscriber.php

**Comment by GrahamCampbell** [comment]
Looks fine to me?

**Comment by goedda** [comment]
There are a lot of constructor injections and arguments, I simply misread. Sorry for the trouble, you can close this one.
