### ISSUE TITLE
Permission of new user group

### ISSUE THREAD

**Issue by goedda** [BootstrapCMS/CMS#128]
I have added a file upload/download system to BootstrapCMS. Only a group should be able to see the links and perform actions, thus, I have 

I. used a Laravel seed to add a new user group 'File Handler' with the permission {"file" : 1}. The seed used your method Credentials::getGroupProvider()->create($group);
II. added $this->setPermissions in the constructor of my controller

    public function __construct()
        {
            $this->setPermissions([
                 'index'	  => 'file',
                 'create'  => 'file',
                 'store'   => 'file',
                 'edit'    => 'file',
                 'update'  => 'file',
                 'destroy' => 'file',
                 'show'	  => 'file',
            ]);

            parent::__construct();
    }

III. Then I used the admin to assign a user to that user group, actually, I assigned the admin itself to that user group. The admin is now assigned to two user groups: admin and file.

But it is not working. I have read the Sentry manual and it should work with multiple user groups as the users themselves do not have any permissions.
The links and the actions are not denied for any user, be it guest, logged in or admin.
It works as it should, if I use one of the pre-defined user groups like 'admin', then only the admin can access the file links and perform the actions in the file controller.

There is no error message or anything, just the blocking is not working with my custom group. Please advice.

**Comment by GrahamCampbell** [comment]
You need to add a new File middleware to https://github.com/BootstrapCMS/Credentials/tree/master/src/Http/Middleware/Auth.

**Comment by goedda** [comment]
Thanks. I will try that asap.
