### ISSUE TITLE
Different themes in admin

### ISSUE THREAD

**Issue by Panoply** [BootstrapCMS/CMS#135]
Firstly, thanks Graham for your work! 

Excuse my english. - I would like to integrate different assets (both bootstrap based) in the admin panel and the actual website. Essentially I want to generate different stylesheets when logged-in to admin panel and different ones when not, separating the administrative styles to the website styles. Ideally, I was thinking something like (I know this is not correct, but for demonstration purposes so you have a better understanding:

if logged-in  {

{!! HTML::style('link-to-stylesheets-admin') !!}

} else {

{!! HTML::style('link-to-stylesheets-website') !!}

}

My project I'm working on will need different layouts and registration to the public will not be available, so it's just for admin. Any insight would be appreciated!

**Comment by rweas** [comment]
Just use \Sentry::check(). If the user is logged in, it will return true, if not, false.

https://cartalyst.com/manual/sentry/2.1#sentry::check()

**Comment by GrahamCampbell** [comment]
NB, you shouldn't bus using sentry directly like that, rather, using it through my Credentials class.

**Comment by GrahamCampbell** [comment]
GrahamCampbell\Credentials\Facades\Credentials::check() will behave in a *similar* way.
