### ISSUE TITLE
How to fix this Error Exception

### ISSUE THREAD

**Issue by makersunion** [BootstrapCMS/CMS#136]
Firstly, thanks Graham for your work!

I have a error exception : 
local.ERROR: exception 'ErrorException' with message 'Invalid argument: function: method 'tags' not found' in /home/vagrant/Code/BootstrapCMS/vendor/laravel/framework/src/Illuminate/Cache/Repository.php:366

I don't know, what is 'tags'? Why 'tags' is method? 
Please help me fix this.
Thanks

**Comment by rweas** [comment]
You need to use a different session system in laravel config.

**Comment by rweas** [comment]
http://laravel.com/docs/5.0/session

**Comment by makersunion** [comment]
@rweas thanks your reply , you mean must use except file session system?

**Comment by rweas** [comment]
Right. Database, red is, etc. File session system doesn't support the tags method

**Comment by makersunion** [comment]
@rweas Oh...I know ,Thank you very much.

**Comment by makersunion** [comment]
PS: Use reds session system show  Class 'Predis\Client' not found , need composer install predis/predis.

**Comment by makersunion** [comment]
@rweas I used predis and config right redis ,still as before 'Invalid argument: function: method 'tags' not found'

**Comment by makersunion** [comment]
Fixed. Need set 
CACHE_DRIVER=redis
SESSION_DRIVER=redis

**Comment by GrahamCampbell** [comment]
This is documented in our readme. To you must use a cache driver that supports tags.

**Comment by GrahamCampbell** [comment]
Nothing to do with sessions.
