### ISSUE TITLE
PostsRepository chokes on pagenation if there are no posts

### ISSUE THREAD

**Issue by DeftNerd** [BootstrapCMS/CMS#139]
If you delete the only post, the pagenation function causes the posts controller to die. 

"[2015-04-23 06:27:52] production.ERROR: exception 'ErrorException' with message 'Argument 1 passed to GrahamCampbell\BootstrapCMS\Repositories\PostRepository::isFirstPage() must be an instance of GrahamCampbell\Credentials\Repositories\Paginator, Illuminate\Pagination\LengthAwarePaginator given' in /srv/www/site/vendor/graham-campbell/credentials/src/Repositories/PaginateRepositoryTrait.php:81"

**Comment by mrrsm** [comment]
The same thing happens with events

**Comment by GrahamCampbell** [comment]
That's not actually caused by deleting the only post by the looks of it.

**Comment by GrahamCampbell** [comment]
We're open to PRs. I don't have time to look into this atm. :)
