### ISSUE TITLE
app:install has the same outcome as app:reset

### ISSUE THREAD

**Issue by DeftNerd** [BootstrapCMS/CMS#141]
Worth considering not truncating the tables during app:install so it doesn't overwrite any live data by mistake. app:reset could truncate the tables before seeding them, and the description of their actions seems to indicate that reset would be the only option that would remove existing data. 

I just noticed it because I was attempting to update the theme and ran app:install instead of app:update by mistake

**Comment by GrahamCampbell** [comment]
Not sure what I can actually do about this?
