### ISSUE TITLE
cms.author setting in footer is nice, but it still hotlinks to your personal github repo

### ISSUE THREAD

**Issue by DeftNerd** [BootstrapCMS/CMS#142]
Might want to add a author_link variable in config/cms.php and change the line from 

&copy; <a href="https://github.com/GrahamCampbell">{{ Config::get('cms.author') }}</a> 2015. All rights reserved.

to 

`@if (Config::get('cms.author_url') && Config::get('cms.author'))`
  `&copy; <a href="{{ Config::get('cms.author_url') }}">{{ Config::get('cms.author') }}</a> {{ date("Y") }}. All rights reserved.`
`@elseif (Config::get('cms.author'))`
  `&copy; <a href="{{ Config::get('APP_URL') }}">{{ Config::get('cms.author') }}</a> {{ date("Y") }}. All rights reserved.`
`@else`
    `&copy; <a href="{{ Config::get('APP_URL') }}">{{ Config::get('APP_URL') }}</a> {{ date("Y") }}. All rights reserved.`
`@endif`

It's OK to put an optional "powered by Bootstrap CMS" with a link to your profile, but saying that you have the copyright on the content isn't proper. Worst case scenario, some despicable site out there uses your CMS and people associate the content with you.

**Comment by DeftNerd** [comment]
See https://github.com/BootstrapCMS/CMS/pull/143

**Comment by GrahamCampbell** [comment]
> but saying that you have the copyright on the content isn't proper.

I do have copyright over the website, but not the content, and you ARE required to retain that as per the AGPLv3 license. The license is different from other licenses because it's very clear that running software on a server still counts as distributing it.
