### ISSUE TITLE
View [] not found. (View: /var/www/html/CMS/resources/views/myviews/register.blade.php)

### ISSUE THREAD

**Issue by Gittinhub** [BootstrapCMS/CMS#148]
return view('myviews.register', $data);  

in app/Htpp/Controllers/mycontroller.php file, laravel returns:

View [] not found. (View: /var/www/html/CMS/resources/views/myviews/register.blade.php)
        ^
        |
Did you see that?   The file name is blank...LOL!!!! 

The file is there and i don't know why it does not open it!!!!  If i change the name for a name of a file that does NOT exists, it returns:
View [notexists.notexists] not found.
Any hint? I think somehow the campbell system is denying it to open a file it doesn't recognize....

**Comment by GrahamCampbell** [comment]
Hmmm, can't replicate? Sorry.

**Comment by Gittinhub** [comment]
do you want the root pass so you see yoursef?

**Comment by Gittinhub** [comment]
btw, what is the user that i should use for the http server? creating a simple user to install this package returns a black page when it is requested ->http://127.0.0.0/  returns blank for a simple user.

**Comment by Gittinhub** [comment]
Hey Campbell.... i see now that error was at:
/var/www/html/CMS/vendor/compiled.php
BUT i did NOW compiled it....
where i check the config to use or not compiled files? How to configure that?

**Comment by GrahamCampbell** [comment]
Just delete the compiled file if you don't want it.

**Comment by Gittinhub** [comment]
Where is it? I did NOT compile it btw. I also added the path to "resources/views/" at config/view.php but didn't work too.

**Comment by GrahamCampbell** [comment]
> I did NOT compile it btw.

Yes, it's automatically generated on install.

**Comment by GrahamCampbell** [comment]
> I also added the path to "resources/views/" at config/view.php but didn't work too.

Don't mess with those files. They work out of the box.

**Comment by Gittinhub** [comment]
Ok, i moved back with original view.php and did a app:reset but still no lucky.
Where are the files i have to delete?

**Comment by GrahamCampbell** [comment]
"/var/www/html/CMS/vendor/compiled.php"

**Comment by Gittinhub** [comment]
File not found. 
I did a app:reset and i see that the error now is in /var/www/html/CMS/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php

**Comment by GrahamCampbell** [comment]
I don't know what you want me to do about it?

**Comment by Gittinhub** [comment]
In my point of view, the cms is not searching at the right place for the view files. The problem is why not. I had some issues about env() not in your cms package, but in other and also slashes and functions like real_path... something that lead us to bugs like that. Did you change something that could lead to an error like that in recent changes? I will start a fresh instalation anyway...

**Comment by GrahamCampbell** [comment]
None of these issues are anything to do with this CMS. I also can't replicate them, so it looks like you are simply "doing it wrong". Sorry, but I can't offer free support for issues unrelated to my software, or indeed at all beyond a reasonable point.

**Comment by Gittinhub** [comment]
OK. Thanks.
