### ISSUE TITLE
having  no file config/navigation.php

### ISSUE THREAD

**Issue by Jamlee** [BootstrapCMS/CMS#149]
I can't find the file config/navigation.php to disable verification emails

**Comment by MatthewLilley** [comment]
You need to publish the configuration files first or they will not be there. Read the documentation.

**Comment by GrahamCampbell** [comment]
Verification emails aren't in that config file anyway.

**Comment by GrahamCampbell** [comment]
https://github.com/BootstrapCMS/CMS/blob/master/config/credentials.php#L38
