### ISSUE TITLE
Markdown editing the contents of a page body

### ISSUE THREAD

**Issue by qrokodial** [BootstrapCMS/CMS#153]
if a person opts out of PHP eval within page bodies, it would be handy to be able to edit the contents via a Markdown editor. this is easier for less technical people to manage content on the website.

this obviously couldn't be a complete replacement for direct HTML editing, but having the option to switch to a simpler Markdown editor would be beneficial.

**Comment by GrahamCampbell** [comment]
Markdown is still way too restrictive for pages imo.
