### ISSUE TITLE
where is a declare of the variable $router

### ISSUE THREAD

**Issue by Jamlee** [BootstrapCMS/CMS#154]
excuse  me,I found the odd variable $router located in `/app/Http/router.php`. but I can't find where the variable was declared . I am a newer to larevel. thinks in advance.

**Comment by GrahamCampbell** [comment]
I require the router file in here, so that's why the variable's set: https://github.com/BootstrapCMS/CMS/blob/master/app/Providers/RouteServiceProvider.php#L57.
