### ISSUE TITLE
Problem with PHP version on Debian 6

### ISSUE THREAD

**Issue by valle6** [BootstrapCMS/CMS#157]
The BootstrapCms looks cool.
I have a server with Debian version 6. PHP is 5.4.35-0 + deb7u2u . I searched on Google and is difficult to install the version of PHP needed to BootstrapCms : 5.5.9 . Considering the importance of this distro , I ask if it is really essential this latest PHP version to BootstrapCms ?

Error:
...
 graham-campbell/security v3.1.0 requires php >=5.5.9 -> your PHP version (5.4.35-0+deb7u2) does not satisfy that requirement.
...

Regards.

**Comment by GrahamCampbell** [comment]
We only support php 5.5.9+.
