### ISSUE TITLE
Make the date and time output more configurable

### ISSUE THREAD

**Issue by mrrsm** [BootstrapCMS/CMS#158]
When displaying and inputting dates and times make the format easily customizable via a config file.  This would be useful for the event datetime picker and displays.

**Comment by GrahamCampbell** [comment]
I'm open to PRs. :)

**Comment by mrrsm** [comment]
How do you feel about changing the default Date/Time input to use the [ISO 8601 standard](http://www.iso.org/iso/home/standards/iso8601.htm) (Also on [Wikipedia](https://en.wikipedia.org/wiki/ISO_8601).  I am finishing up a pull request for this and wanted to use a more generic date time format if you would approve it.
