### ISSUE TITLE
if i don't need email activation,the program still send email.

### ISSUE THREAD

**Issue by Jamlee** [BootstrapCMS/CMS#159]
this code taken from:
/home/jamlee/WORK/www/lrlcms/webroot/project/vendor/graham-campbell/credentials/src/Http/Controllers/RegistrationController.php

            if (!Config::get('credentials.activation')) {
                $mail = [
                    'url'     => URL::to(Config::get('core.home', '/')),
                    'email'   => $user->getLogin(),
                    'subject' => Config::get('core.name').' - Welcome',
                ];
                Mail::queue('credentials::emails.welcome', $mail, function ($message) use ($mail) {
                    $message->to($mail['email'])->subject($mail['subject']);
                });

                $user->attemptActivation($user->getActivationCode());
                $user->addGroup(Credentials::getGroupProvider()->findByName('Users'));

                return Redirect::to(Config::get('core.home', '/'))
                    ->with('success', 'Your account has been created successfully.');
            }

**Comment by GrahamCampbell** [comment]
As you can see from the code sample, that email send out is not an activation email, it's a welcome email.

**Comment by Jamlee** [comment]
sorry , I haven't read  that carefully, @GrahamCampbell
