### ISSUE TITLE
AGPL license

### ISSUE THREAD

**Issue by appkr** [BootstrapCMS/CMS#162]
Last couple of days, I have been studying this package. In the course of studying, I found that it is under AGPL. As far as I know, the AGPL forces its user to open his/her all derivative reworks/modified codes to the public again. What that means is that, if I make an internet service using this package, I have to make all of my service code be available/downloadable to anyone/everyone. Then I cannot use this for a commercial purpose, since it's in danger in terms of security. Do I understan your intention of licensing policy and the AGPL license itself correctly?

**Comment by GrahamCampbell** [comment]
Yes, that is the intention. I want this to be a learning resource and to be shared.

**Comment by appkr** [comment]
It's said because I like your code much. Anyway good leaning resource though. I hope there is clear statement of your intention on the readme.
