### ISSUE TITLE
Dependency on deprecated lightgear/asset

### ISSUE THREAD

**Issue by jwilson8767** [BootstrapCMS/CMS#165]
BootstrapCMS/logviewer caries over a dependency on [lightgear/asset](https://github.com/lightgear/asset) which is now discontinued. The author of this package advises usage of Gulp/Elixir instead.

I suggest this be implemented in the default BootstrapCMS/CMS package as part of the default setup. Any objections?

**Comment by GrahamCampbell** [comment]
It's not discountinued.

**Comment by GrahamCampbell** [comment]
We also don't even use that package.

**Comment by GrahamCampbell** [comment]
We use https://github.com/BootstrapCMS/Asset.

**Comment by GrahamCampbell** [comment]
> advises usage of Gulp/Elixir instead.

Yeh, I know. I planned to move to gulp a few months back, but never found the time.

**Comment by jwilson8767** [comment]
Geez, you are right on the ball. Great response time!

Ok, I see the BootstrapCMS/Asset package, but only see lightgear/asset required in BootstrapCMS/Logviewer's composer.json. What am I missing?

**Comment by jwilson8767** [comment]
>I planned to move to gulp a few months back, but never found the time.

Would it help if I put this together as a pull request?

**Comment by GrahamCampbell** [comment]
That would be really helpful if you could. All repos in this org are affected though, which is why I've not had the time yet.
