### ISSUE TITLE
  CMS not pulling latest BootstrapCMS/Credentials into vendor folder

### ISSUE THREAD

**Issue by Drethic** [BootstrapCMS/CMS#166]
I followed the setup directions and got the site working as expected.  I then went into events and deleted the default one that is there.  This triggered an error in graham-campbell/credentials/src/Repositories/PaginateRepositoryTrait.php(78).  After some investigation I found the error had already been corrected in Bootstrap/Credentials at the end of May.  Based on the composer.lock file I found the reference commit listed as, "82f4cfac22775d3af3d6fd3b8cb11b38cbdba7cf".  I ran composer update and it did not pull down an updated copy of credentials.  I went to https://api.github.com/repos/BootstrapCMS/Credentials/zi
pball without the reference and got the latest code with the fix.

I'm afraid I'm still new to using composer so I can't offer a solution, but I hope it's an easy fix for you.  In the short term I applied the change on line 78 to bypass the bug.

**Comment by GrahamCampbell** [comment]
Yeh, I know. I'm working on this atm.
