### ISSUE TITLE
Switch to Elixir for building instead of laravel-core.

### ISSUE THREAD

**Issue by jwilson8767** [BootstrapCMS/CMS#174]
Totally opinionated, but it's possible to use Elixir for the three commands laravel-core adds, thereby removing one more dep from the project.

The advantage is that it cleans up the install process by consolidating steps 4 and 5.

Thoughts? I'll pr if you like the idea.

**Comment by GrahamCampbell** [comment]
Sorry, don't like that. Laravel core was created for the exact purpose of installing projects. Infact, laravel core should really be running gulp for us, not the other way around. :)

**Comment by jwilson8767** [comment]
Ha, good point.
