### ISSUE TITLE
Install step 4

### ISSUE THREAD

**Issue by YounessTayer** [BootstrapCMS/CMS#176]
Hi Graham;
The command line "gulp --production" in the step 4 of your install guide does not work.
This command line is it mandatory?
Youness Tayer.

**Comment by GrahamCampbell** [comment]
> This command line is it mandatory?

Yes. Try running `node-modules\.bin\gulp`.

**Comment by YounessTayer** [comment]
node-modules/.bin/gulp. Does not work, I have no  the ".bin" folder under the "node-modules" folder

**Comment by GrahamCampbell** [comment]
Looks like you didn't run `npm install` then.

**Comment by YounessTayer** [comment]
First, I got the following warn message when I run "npm install": 
"npm WARN optional dep failed, continuing fsevents@0.3.8"

I also got the following error messag: "bower ENOENT   No bower.json present"  when I run "bower install"  from the "bootstrap-cms" folder.

**Comment by jwilson8767** [comment]
@YounessTayer are you trying to run npm on a VM?

**Comment by YounessTayer** [comment]
Hi. No, I am using LAMP on a local machine.

2015-08-27 21:38 GMT+02:00 jwilson8767 <notifications@github.com>:
