### ISSUE TITLE
Unable to Update Pages, Posts, or Users

### ISSUE THREAD

**Issue by Drethic** [BootstrapCMS/CMS#179]
I updated from commit 9dadd81 to eb4d63c ( current head as of 7 days ago ).  I moved all the config information from the config/*.php to .env and merged the one file change I did.  I ran php artisan app:install instead of php artisan app:update so all my users reset.  I also did gulp --production.  This wouldn't be a problem except I am not able to change the default users email addresses.  When I hit save it goes to the show for the user, in this case users/4.  However, there is no change in the email address.  I'm logged in as user 1 so I should have full rights to make the change.  In addition, I tried to do a minor change to the home page.  After I click save I go back to the home page and the change is not there, nor is it in the database.

I'm sure there is a config or permission I missed but I'm at a loss as to where.  Any suggestions would be appreciated.

Edit:
I did a fresh file install, and I am still not able to modify users, pages, or posts.  I haven't tried blog or events.  Going to try a fresh database next.

Edit 2:
Same result with a fresh database.  I've also restarted httpd and mysqld to clear out any cache from there, as well as run php artisan cache:clear.

**Comment by nicklee1990** [comment]
+1 I am also seeing this issue

**Comment by damon8765** [comment]
Something went wrong on our servers while we were processing your request. An error has occurred and this resource cannot be displayed. This occurrence has been logged, and a highly trained team of monkeys has been dispatched to deal with your problem. We're really sorry about this, and will work hard to get this resolved as soon as possible.

This error can be identified by c8d08dbf-b8f7-4453-a47d-bef1d013f709. You might want to take a note of this code.

Perhaps you would like to go to our home page?

**Comment by GrahamCampbell** [comment]
Could you please give me information from the logs. The error pages tell you nothing on purpose for security reasons.

**Comment by GrahamCampbell** [comment]
> This error can be identified by c8d08dbf-b8f7-4453-a47d-bef1d013f709. You might want to take a note of this code.

That error code just identifies that particular occurrence so you can look it up in the logs.

**Comment by damon8765** [comment]
[2015-08-31 08:24:49] production.ERROR: exception 'RuntimeException' with message 'No supported encrypter found. The cipher and / or key length are invalid.' in /Users/damon/Documents/Code/CMS/bootstrap/cache/compiled.php:6693
Stack trace:

**Comment by GrahamCampbell** [comment]
Looks like you haven't actually run `php artisan app:install`.

**Comment by damon8765** [comment]
Already running

**Comment by GrahamCampbell** [comment]
Well, you haven't set an encryption key, which that command does for you.

**Comment by GrahamCampbell** [comment]
Basically, the fact that this isn;t working now and was before is because of a security fix in laravel.

**Comment by GrahamCampbell** [comment]
You need to set a secure encryption key.

**Comment by damon8765** [comment]
ok  Thank you！

**Comment by nicklee1990** [comment]
the app key wasn't the issue I was seeing, my key was set correctly. @damon8765 please create separate issues if you are experiencing a different problem as it is confusing/misleading - if you read the OP's description it isn't the same as what you were seeing

@GrahamCampbell There wasn't anything being displayed in the logs, it just redirects me back after attempting to save with no success/fail message and without updating the page. I'll look into it again this afternoon - my first thought was something middleware related but haven't had time to check

**Comment by Drethic** [comment]
@GrahamCampbell I agree with @nicklee1990, I have my App Key set, and am just redirected back to the show page with no error, nothing in the logs, and debug enabled.

**Comment by Drethic** [comment]
@nicklee1990 based on the new PR that was merged in the Pages and Posts have been fixed.  I put in a pull request for Credentials to apply that change to Account Details, Account Passwords, and User Edit.  I'm also going to put one in against CMS for Events a couple minor fixes.
