### ISSUE TITLE
what?

### ISSUE THREAD

**Issue by damon8765** [BootstrapCMS/CMS#180]
Internal Server Error
What does this mean?

Something went wrong on our servers while we were processing your request. An error has occurred and this resource cannot be displayed. This occurrence has been logged, and a highly trained team of monkeys has been dispatched to deal with your problem. We're really sorry about this, and will work hard to get this resolved as soon as possible.

This error can be identified by 2249dd9d-1975-42fd-8c7c-ff6419765c05. You might want to take a note of this code.

Perhaps you would like to go to our home page?

**Comment by GrahamCampbell** [comment]
No idea. Look in the logs please.

**Comment by LeeMing988** [comment]
php artisan key:generate will fix the issue @damon8765

**Comment by GrahamCampbell** [comment]
> php artisan key:generate will fix the issue @damon8765

Not nessesarely. That 500 page can turn up for ANY reason.

**Comment by GrahamCampbell** [comment]
Closing because of no response from @damon8765.
