### ISSUE TITLE
"Cannot send message without a sender address" when send the Contact form

### ISSUE THREAD

**Issue by miharbi** [BootstrapCMS/CMS#186]
Im trying to fix that but I didn't get it. look what is printing when I do dd() in 
/vendor/graham-campbell/contact/src/Mailer.php line 122
       
        $this->mail->queue('contact::message', $mail, function ($message) use ($mail) {
            $message->to($mail['email'])->subject($mail['subject']); dd($mail);
        });

array:7 [▼
  "email" => "valid@email.com"
  "subject" => "Bootstrap CMS - New Message"
  "platform" => "Bootstrap CMS"
  "url" => "http:/bootstrap.cms"
  "contact" => "valid@email.com"
  "name" => "Miharbi Hernandez"
  "quote" => "Lacus, nunc rhoncus mattis turpis nec dictumst phasellus dictumst penatibus tristique nascetur aliquet platea odio nisi montes, turpis augue! Elementum."
]

But if I move the dd after the queue I get: 

"Swift_TransportException thrown with message "Cannot send message without a sender address"

Stacktrace:
#59 Swift_TransportException in /home/vagrant/Code/infinity/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php:162
#58 Swift_Transport_AbstractSmtpTransport:send in /home/vagrant/Code/infinity/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mailer.php:85
#57 Swift_Mailer:send in /home/vagrant/Code/infinity/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php:398
#56 Illuminate\Mail\Mailer:sendSwiftMessage in /home/vagrant/Code/infinity/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php:188
#55 Illuminate\Mail\Mailer:send in /home/vagrant/Code/infinity/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php:293
#54 Illuminate\Mail\Mailer:handleQueuedMessage in /home/vagrant/Code/infinity/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php:129
#53 Illuminate\Queue\Jobs\Job:resolveAndFire in /home/vagrant/Code/infinity/vendor/laravel/framework/src/Illuminate/Queue/Jobs/SyncJob.php:44
#52 Illuminate\Queue\Jobs\SyncJob:fire in /home/vagrant/Code/infinity/vendor/laravel/framework/src/Illuminate/Queue/SyncQueue.php:27
#51 Illuminate\Queue\SyncQueue:push in /home/vagrant/Code/infinity/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php:204
#50 Illuminate\Mail\Mailer:queue in /home/vagrant/Code/infinity/vendor/graham-campbell/contact/src/Mailer.php:122
#49 GrahamCampbell\Contact\Mailer:sendMessage in /home/vagrant/Code/infinity/vendor/graham-campbell/contact/src/Mailer.php:94
#48 GrahamCampbell\Contact\Mailer:send in /home/vagrant/Code/infinity/bootstrap/cache/compiled.php:5725
#47 Illuminate\Support\Facades\Facade:__callStatic in /home/vagrant/Code/infinity/vendor/graham-campbell/contact/src/Http/Controllers/ContactController.php:82
#46 GrahamCampbell\Contact\Facades\Mailer:send in /home/vagrant/Code/infinity/vendor/graham-campbell/contact/src/Http/Controllers/ContactController.php:82
#45 GrahamCampbell\Contact\Http\Controllers\ContactController:postSubmit in <#unknown>:0
#44 call_user_func_array in /home/vagrant/Code/infinity/bootstrap/cache/compiled.php:8490
#43 Illuminate\Routing\Controller:callAction in /home/vagrant/Code/infinity/bootstrap/cache/compiled.php:8559
#42 Illuminate\Routing\ControllerDispatcher:call in /home/vagrant/Code/infinity/bootstrap/cache/compiled.php:8539
#41 Illuminate\Routing\ControllerDispatcher:Illuminate\Routing\{closure} in <#unknown>:0
#40 call_user_func in /home/vagrant/Code/infinity/bootstrap/cache/compiled.php:9196
#39 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in <#unknown>:0
#38 call_user_func in /home/vagrant/Code/infinity/bootstrap/cache/compiled.php:9178
#37 Illuminate\Pipeline\Pipeline:then in /home/vagrant/Code/infinity/bootstrap/cache/compiled.php:8540
#36 Illuminate\Routing\ControllerDispatcher:callWithinStack in /home/vagrant/Code/infinity/bootstrap/cache/compiled.php:8525
#35 Illuminate\Routing\ControllerDispatcher:dispatch in /home/vagrant/Code/infinity/bootstrap/cache/compiled.php:7500
#34 Illuminate\Routing\Route:runWithCustomDispatcher in /home/vagrant/Code/infinity/bootstrap/cache/compiled.php:7471
#33 Illuminate\Routing\Route:run in /home/vagrant/Code/infinity/bootstrap/cache/compiled.php:7124
#32 Illuminate\Routing\Router:Illuminate\Routing\{closure} in <#unknown>:0
#31 call_user_func in /home/vagrant/Code/infinity/bootstrap/cache/compiled.php:9196
#30 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in <#unknown>:0
#29 call_user_func in /home/vagrant/Code/infinity/bootstrap/cache/compiled.php:9178
#28 Illuminate\Pipeline\Pipeline:then in /home/vagrant/Code/infinity/bootstrap/cache/compiled.php:7125
#27 Illuminate\Routing\Router:runRouteWithinStack in /home/vagrant/Code/infinity/bootstrap/cache/compiled.php:7113
#26 Illuminate\Routing\Router:dispatchToRoute in /home/vagrant/Code/infinity/bootstrap/cache/compiled.php:7098
#25 Illuminate\Routing\Router:dispatch in /home/vagrant/Code/infinity/bootstrap/cache/compiled.php:2088
#24 Illuminate\Foundation\Http\Kernel:Illuminate\Foundation\Http\{closure} in <#unknown>:0
#23 call_user_func in /home/vagrant/Code/infinity/bootstrap/cache/compiled.php:9196
#22 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /home/vagrant/Code/infinity/bootstrap/cache/compiled.php:12456
#21 Illuminate\View\Middleware\ShareErrorsFromSession:handle in <#unknown>:0
#20 call_user_func_array in /home/vagrant/Code/infinity/bootstrap/cache/compiled.php:9188
#19 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /home/vagrant/Code/infinity/bootstrap/cache/compiled.php:11104
#18 Illuminate\Session\Middleware\StartSession:handle in <#unknown>:0
#17 call_user_func_array in /home/vagrant/Code/infinity/bootstrap/cache/compiled.php:9188
#16 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /home/vagrant/Code/infinity/bootstrap/cache/compiled.php:12193
#15 Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse:handle in <#unknown>:0
#14 call_user_func_array in /home/vagrant/Code/infinity/bootstrap/cache/compiled.php:9188
#13 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /home/vagrant/Code/infinity/bootstrap/cache/compiled.php:12132
#12 Illuminate\Cookie\Middleware\EncryptCookies:handle in <#unknown>:0
#11 call_user_func_array in /home/vagrant/Code/infinity/bootstrap/cache/compiled.php:9188
#10 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /home/vagrant/Code/infinity/app/Http/Middleware/CheckForMaintenanceMode.php:68
#9 GrahamCampbell\BootstrapCMS\Http\Middleware\CheckForMaintenanceMode:handle in <#unknown>:0
#8 call_user_func_array in /home/vagrant/Code/infinity/bootstrap/cache/compiled.php:9188
#7 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /home/vagrant/Code/infinity/vendor/fideloper/proxy/src/TrustProxies.php:47
#6 Fideloper\Proxy\TrustProxies:handle in <#unknown>:0
#5 call_user_func_array in /home/vagrant/Code/infinity/bootstrap/cache/compiled.php:9188
#4 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in <#unknown>:0
#3 call_user_func in /home/vagrant/Code/infinity/bootstrap/cache/compiled.php:9178
#2 Illuminate\Pipeline\Pipeline:then in /home/vagrant/Code/infinity/bootstrap/cache/compiled.php:2035
#1 Illuminate\Foundation\Http\Kernel:sendRequestThroughRouter in /home/vagrant/Code/infinity/bootstrap/cache/compiled.php:2018
#0 Illuminate\Foundation\Http\Kernel:handle in /home/vagrant/Code/infinity/public/index.php:54
"

**Comment by GrahamCampbell** [comment]
You need to correctly configure mail.php, and make sure you clear the config cache after you make any changes to the config, otherwise none of the changes you've made will get use.

**Comment by miharbi** [comment]
Yeah, my fail. I subject to use 
'from' => ['address' => env('MAIL_FROMADDRESS', null), 'name' => env('MAIL_FROMNAME', null)],

Thanks a lot man.

**Comment by GrahamCampbell** [comment]
np
