### ISSUE TITLE
Problems encountered during installation

### ISSUE THREAD

**Issue by XingFang** [BootstrapCMS/CMS#190]
hello！When I according to your installation steps to complete the project , with the browser open the project has the wrong page, what is the reason? Error page shows "Error 500" and says "This error can be identified by 28f656ad-8d55-4891-8812-36023ff61856. You might want to take a note of this code." ,  I was a Laravel beginner,This is a little difficult for me ! hlep me ! thank you !

**Comment by GrahamCampbell** [comment]
I can't do anything without logs.

**Comment by GrahamCampbell** [comment]
That error code was provided so that you can look it up in your logs.

**Comment by XingFang** [comment]
this is log ....
[2015-09-09 07:42:43] local.ERROR: exception 'RuntimeException' with message 'No supported encrypter found. The cipher and / or key length are invalid.' in E:\WWW\CMS-master\bootstrap\cache\compiled.php:6693
Stack trace:
#0 E:\WWW\CMS-master\bootstrap\cache\compiled.php(1068): Illuminate\Encryption\EncryptionServiceProvider->Illuminate\Encryption\{closure}(Object(Illuminate\Foundation\Application), Array)
#1 E:\WWW\CMS-master\bootstrap\cache\compiled.php(1021): Illuminate\Container\Container->build(Object(Closure), Array)
#2 E:\WWW\CMS-master\bootstrap\cache\compiled.php(1559): Illuminate\Container\Container->make('encrypter', Array)
#3 E:\WWW\CMS-master\bootstrap\cache\compiled.php(1113): Illuminate\Foundation\Application->make('Illuminate\\Cont...')
#4 E:\WWW\CMS-master\bootstrap\cache\compiled.php(1097): Illuminate\Container\Container->resolveClass(Object(ReflectionParameter))
#5 E:\WWW\CMS-master\bootstrap\cache\compiled.php(1083): Illuminate\Container\Container->getDependencies(Array, Array)
#6 E:\WWW\CMS-master\bootstrap\cache\compiled.php(1021): Illuminate\Container\Container->build('Illuminate\\Cook...', Array)
#7 E:\WWW\CMS-master\bootstrap\cache\compiled.php(1559): Illuminate\Container\Container->make('Illuminate\\Cook...', Array)
#8 E:\WWW\CMS-master\bootstrap\cache\compiled.php(2042): Illuminate\Foundation\Application->make('Illuminate\\Cook...')
#9 E:\WWW\CMS-master\public\index.php(57): Illuminate\Foundation\Http\Kernel->terminate(Object(Illuminate\Http\Request), Object(Illuminate\Http\Response))
#10 {main} {"identification":{"id":"c9388770-489c-45bd-80cb-a2dab89759f7"}}

**Comment by GrahamCampbell** [comment]
You need to generate an encryption key. Please see laravel's docs on that.

**Comment by XingFang** [comment]
that's ok!!  when i run command php artisan key:generate,everythis is OK!!!  thiank you very much!
