### ISSUE TITLE
'Undefined index: _method' in views\pages\form.blade.php

### ISSUE THREAD

**Issue by g-p-c-s** [BootstrapCMS/CMS#191]
`<input type="hidden" name="_method" value="{{ $form['_method'] }}">`

**Comment by miharbi** [comment]
https://github.com/BootstrapCMS/CMS/blob/master/resources/views/pages/edit.blade.php in the line 30 (if you have the source updated), you should have '_method' => 'PATCH',  before @include('pages.form')

**Comment by miharbi** [comment]
mmm ok, that is in creation.... you right, there is a bug

**Comment by GrahamCampbell** [comment]
Thanks guys.

**Comment by g-p-c-s** [comment]
(y)
