### ISSUE TITLE
UPDATE method isn't execut under the USERController

### ISSUE THREAD

**Issue by XingFang** [BootstrapCMS/CMS#193]
Hello , I came again, I'm not sure if this is the case of others , when I use the administrator account edit common user information and click SAVE USER, can not enter the UPDATE method , but automatically jump to user details page , user information is not changed, there is no message to tell you what happened ,Even if the UPDATE method is annotated,No effect for this project. You encountered this problem?

**Comment by miharbi** [comment]
https://github.com/BootstrapCMS/CMS/pull/185#event-401909708 it was solved

**Comment by XingFang** [comment]
Why do I still have such a problem , is it version of the problem ? This is what I did yesterday downloaded from GrahamCampbell's github

**Comment by miharbi** [comment]
There isn't a stable version yet, remember that it still in Alpha https://github.com/BootstrapCMS/CMS/releases/tag/v0.9.0-alpha but this particular problem was solved.

**Comment by XingFang** [comment]
Thinks for your help!!
