### ISSUE TITLE
Delete Log

### ISSUE THREAD

**Issue by luis24** [BootstrapCMS/CMS#196]
Can't delete a log. It throws a http exception.

There's a piece of code missing on the confirmation button. 

I think it should be:
![screen shot 2015-09-30 at 3 25 13 pm](https://cloud.githubusercontent.com/assets/3614119/10204769/80947fcc-6787-11e5-9491-debef070996f.png)

**Comment by GrahamCampbell** [comment]
I think the current code is ok is it not?

**Comment by GrahamCampbell** [comment]
What error are you getting?

**Comment by luis24** [comment]
When I try do delete the current log and press "Yes" It throws a NotFoundHttpException because it's sending me to the url "http://test.app/logviewer/2015-09-30/logviewer/2015-09-30/delete"

**Comment by GrahamCampbell** [comment]
Right, errr.

**Comment by GrahamCampbell** [comment]
I'll look into this at the weekend. :)

**Comment by luis24** [comment]
My bad, this issue should be in <a href="https://github.com/BootstrapCMS/LogViewer">LogViewer</a> not here. I think I made it work but after the current log is deleted it shows this log:

<code>[2015-10-06 22:33:19] local.ERROR: exception 'GrahamCampbell\LogViewer\Log\FilesystemException' with message 'The log(s) could not be located.' in /home/vagrant/Code/test/vendor/graham-campbell/logviewer/src/Log/Filesystem.php:69 </code>

It should show the message "There are no logs!", shouldn't it?
