### ISSUE TITLE
where is the cms-main.css?

### ISSUE THREAD

**Issue by elwolfy** [BootstrapCMS/CMS#197]
I know that this not is very important. 
But I need evaluate the Bootstrap CM look and feel. 

How I can get the cms-main.css?

**Comment by GrahamCampbell** [comment]
You need to build it by running gulp.

**Comment by josebispo** [comment]
You can try use the node with gulp after of download.
npm install gulp if you have some error use npm install (name-module).
.

**Comment by elwolfy** [comment]
Thank. very much. It is working and excelent look and feel.

Jorge.

2015-10-08 12:07 GMT-05:00 Graham Campbell <notifications@github.com>:
