### ISSUE TITLE
Rename Home, Contact and About in Title Items of Navigator Menu

### ISSUE THREAD

**Issue by elwolfy** [BootstrapCMS/CMS#198]
I am trying to rename this elements of navigator menu and nothing is working with it.

How I can rename Home, contact and about title items of Nvigator Menu?

Regards.

**Comment by GrahamCampbell** [comment]
Go to "edit" each page.

**Comment by elwolfy** [comment]
One time more: thanks very much.

I am thinking about add support multilanguage and add links to social
network such as twitter, facebook and linkedin in the pages of CMS
Bootstrap.

Regards.

2015-10-09 18:06 GMT-05:00 Graham Campbell <notifications@github.com>:
