### ISSUE TITLE
Blank page?

### ISSUE THREAD

**Issue by qq280948982** [BootstrapCMS/CMS#199]
when I setup followed README, I started the server from CMD type "php artisan serve", every thing is well without report any errors, but when I visit the http://localhost:8000, I get a blank page, I noticed the url was redirected to "/pages/home", but I cannot found the "home" method in "PageController", and then I try to change the url to "pages/show", also a blank page again, is there anything I missed to do?

**Comment by qq280948982** [comment]
btw, I had generate the key from type "php artisan key:generate", and I have checked the log in /project/storage/logs/laravel-2015-10-28.log file, it's nothing any log in it.

**Comment by qq280948982** [comment]
I have uninstall all and rebuild again, now the home page can be showed, but some .js and .css could not loaded, it returns 404, how to fixed it?

**Comment by GrahamCampbell** [comment]
Looks like you haven't run gulp correctly.

**Comment by rudolphp** [comment]
I installed as per the instructions in README file. But in browser I get below error

Error 500
Houston, We Have A Problem.
This error can be identified by a3e903e7-13b3-4cf7-b24f-ccf949813310. You might want to take a note of this code.

Where do I find the actual error?

**Comment by GrahamCampbell** [comment]
Look the logs in the storage folder.

**Comment by rudolphp** [comment]
its working now. 
a) is there a superuser admin. which can control everything like users etc.
b) I registered and logged in, but cannot see options to add new content like blog post and events.

thank you

**Comment by GrahamCampbell** [comment]
You shouldn't register. You need to login as the default user and change the email.

**Comment by GrahamCampbell** [comment]
See https://github.com/BootstrapCMS/CMS/blob/master/app/Seeds/UsersTableSeeder.php for all the out of the box users.

**Comment by qq280948982** [comment]
thx a lot, I have missing gulp step, and now is working
