### ISSUE TITLE
Rename Blog to News?

### ISSUE THREAD

**Issue by daviestar** [BootstrapCMS/CMS#200]
Hey,

I've been hunting for a while for a way to change both the nav title and route from 'Blog' to 'News' if someone could point me in the right direction?

Changing the route `$router->get('blog', ['as' => 'blog', function () {...}]);` to 'news' doesn't appear to change anything.

Thanks.

**Comment by GrahamCampbell** [comment]
Probably because you didn't recache the routes.

**Comment by daviestar** [comment]
Hi again,

Is there any way to rename 'Blog' in the navigation bar?

I have run the command `php artisan route:cache`, and I've blown away all the files in the `storage` folder.

When I change the route to `$router->get('news', ['as' => 'blog', function () {...}]);` and visit `app.dev/blog` it still takes me to the news page, although `app.dev/news` does now appear to redirect to `app.dev/blog`.
