### ISSUE TITLE
Suspended registration ?

### ISSUE THREAD

**Issue by DeeJaVu** [BootstrapCMS/CMS#202]
So i was testing my mail server, this way i registered 4-5 times to receive an activation code, finally i can receuive email, but now whenever i try to register i get this error "You have been suspended from registration. Please contact support." ? what can i do to fix this pls help

**Comment by GrahamCampbell** [comment]
When you spam the registration page, as a security measure, we lock you out.

**Comment by GrahamCampbell** [comment]
Just clear you cache to reset the rate limits on the registration.

**Comment by GrahamCampbell** [comment]
> Please contact support.

That was referring to the user contacting the webmaster btw, rather than the webmaster contacting me. ;)

**Comment by DeeJaVu** [comment]
Thank its working again :)
