### ISSUE TITLE
App did not run because of missing directories

### ISSUE THREAD

**Issue by tehthird** [BootstrapCMS/CMS#206]
Hello, maybe you have been told but I just downloaded and installed this CMS, and ran in to some trouble when running it for the first time. It just gave a view of "404 houston we have a problem" or something, with laravel log cryptically said: local.ERROR: exception 'ErrorException' with message 'file_put_contents(): etc,

I fixed this by making the folders "storage/framework/views" and "storage/framework/session". 

Could these not be auto created on build, to prevent this from happening? In my head a simple solution but Im no expert here. Thanks!

**Comment by GrahamCampbell** [comment]
Yeh, that's needed to use the file session driver. ;)

**Comment by tehthird** [comment]
Sorry Graham, i guess it was me because I just did a reinstall without this problem

**Comment by GrahamCampbell** [comment]
Yes, this folder does already exist in the code: https://github.com/BootstrapCMS/CMS/tree/master/storage/framework/sessions.
