### ISSUE TITLE
Delete current log gives an error.

### ISSUE THREAD

**Issue by shinokada** [BootstrapCMS/CMS#207]
Just FYI.

When I delete a current log, it goes to url of http://localhost:8000/logviewer/2016-01-27/logviewer/2016-01-27/delete and gives and error 404.

**Comment by DeeJaVu** [comment]
i opened a new pull request to fix this simple isue https://github.com/BootstrapCMS/LogViewer/pull/6

**Comment by BenJule** [comment]
i can confirm this!

**Comment by abedputra** [comment]
how to fix this?

**Comment by GrahamCampbell** [comment]
Fixed in the dev version of logviewer.
