### ISSUE TITLE
Upgrade to Laravel 5.2

### ISSUE THREAD

**Issue by akalongman** [BootstrapCMS/CMS#209]
When you plan upgrade to Laravel 5.2?

**Comment by GrahamCampbell** [comment]
I don't plan to upgrade.

**Comment by akalongman** [comment]
Reason?

**Comment by GrahamCampbell** [comment]
Unless there is a reason to upgrade, then I'm not upgrading.

**Comment by GrahamCampbell** [comment]
Laravel 5.1 is LTS.

**Comment by akalongman** [comment]
Ok. Do you plan support and maintain this project in future?

**Comment by GrahamCampbell** [comment]
Yes, but L5.1 is supported for 3 years, so I won't upgrade until the next laravel LTS version.

**Comment by GrahamCampbell** [comment]
Means that what time I do give to this project can be better focused on more important things.
