### ISSUE TITLE
PHP 7 support

### ISSUE THREAD

**Issue by Haafiz** [BootstrapCMS/CMS#210]
Does this project support PHP 7?  Have you guys tried it? If no then is there a plan to make it support PHP7 ?

**Comment by GrahamCampbell** [comment]
It should support php 7, yes.

**Comment by Haafiz** [comment]
I agree and understand that you have closed it but I am worried about this change:
http://php.net/manual/en/migration70.incompatible.php#migration70.incompatible.variable-handling.indirec

Can you once again check this?

**Comment by GrahamCampbell** [comment]
I'm very familiar with the changes in PHP 7, and if you find an actual issues, please let me know.
