### ISSUE TITLE
Install issue php artisan app:install

### ISSUE THREAD

**Issue by wcousin** [BootstrapCMS/CMS#212]
I am getting this error on install:

php artisan app:install
PHP Fatal error:  Uncaught exception 'ReflectionException' with message 'Class GrahamCampbell\BootstrapCMS\Console\Kernel does not 
exist' in /home/   ...    /vendor/laravel/framework/src/Illuminate/Container/Container.ph
p:738                                                                                                         

How can I fix this?

**Comment by GrahamCampbell** [comment]
Looks like you forgot to run composer install.
