### ISSUE TITLE
Error after install

### ISSUE THREAD

**Issue by wcousin** [BootstrapCMS/CMS#215]
I have everything installed but I keep getting this error when I try to navigate to localhost:8000 -

> No supported encrypter found. The cipher and / or key length are invalid.
/Applications/MAMP/htdocs/bootstrap/cache/compiled.php
            ```
$key = $config['key'];
            $cipher = $config['cipher'];
            if (Encrypter::supported($key, $cipher)) {
                return new Encrypter($key, $cipher);
            } elseif (McryptEncrypter::supported($key, $cipher)) {
                return new McryptEncrypter($key, $cipher);
            } else {
                throw new RuntimeException('No supported encrypter found. The cipher and / or key length are invalid.');
            }
        });
```
I have generated a new key with `php artisan key:generate` , updated the new key in app.php with no success. 

Additionally, I installed it on DigitalOcean.com with success, but the index.php page shows a server 500 error.  

Any help on either of these issues? On DigitalOcean I installed in the root.

**Comment by GrahamCampbell** [comment]
Looks like you've forgotten to set an encryption key.
