### ISSUE TITLE
PHP Fatal error:  Uncaught ReflectionException: Class log does not exist 

### ISSUE THREAD

**Issue by Haafiz** [BootstrapCMS/CMS#216]
After last composer update I am getting this error:

`PHP Fatal error:  Uncaught ReflectionException: Class log does not exist in ...dynamic/vendor/laravel/framework/src/Illuminate/Container/Container.php:741
Stack trace:
#0 .../dynamic/vendor/laravel/framework/src/Illuminate/Container/Container.php(741): ReflectionClass->__construct('log')
#1 ..../dynamic/vendor/laravel/framework/src/Illuminate/Container/Container.php(631): Illuminate\Container\Container->build('log', Array)
#2 .../dynamic/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(674): Illuminate\Container\Container->make('log', Array)
#3.../dynamic/vendor/graham-campbell/exceptions/src/ExceptionHandler.php(64): Illuminate\Foundation\Application->make('log')
#4 [internal function]: GrahamCampbell\Exceptions\ExceptionHandler->__construct(Object(Illuminate\Foundation\Application))
#5 .../vendor/laravel/framework/src/Illuminate/Container/Container.php(780): ReflectionClass->newInstanceArgs(A in .../dynamic/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 741
Script php artisan clear-compiled handling the pre-update-cmd event returned with an error

                                                                                                                                                       
  [RuntimeException]                                                                                                                                   
  Error Output: PHP Fatal error:  Uncaught ReflectionException: Class log does not exist in .../dynamic/vendor/laravel/framework/sr  
  c/Illuminate/Container/Container.php:741                                                                                                             
  Stack trace:                                                                                                                                         
  #0 .../dynamic/vendor/laravel/framework/src/Illuminate/Container/Container.php(741): ReflectionClass->__construct('log')           
  #1 .../dynamic/vendor/laravel/framework/src/Illuminate/Container/Container.php(631): Illuminate\Container\Container->build('log',  
   Array)                                                                                                                                              
  #2 ../dynamic/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(674): Illuminate\Container\Container->make('log  
  ', Array)                                                                                                                                            
  #3 ../dynamic/vendor/graham-campbell/exceptions/src/ExceptionHandler.php(64): Illuminate\Foundation\Application->make('log')      
  #4 [internal function]: GrahamCampbell\Exceptions\ExceptionHandler->__construct(Object(Illuminate\Foundation\Application))                           
  #5 ..dynamic/vendor/laravel/framework/src/Illuminate/Container/Container.php(780): ReflectionClass->newInstanceArgs(A in /var/w  
 ../dynamic/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 741      `

My understanding is that  it is something being done from Exceptions package. And now no matter what I do, I face this error. In both command line as well in browser. So what should be done?

**Comment by GrahamCampbell** [comment]
**never** run composer update.

**Comment by GrahamCampbell** [comment]
Bootstrap CMS contains a composer.lock on purpose so it actually works.

**Comment by Haafiz** [comment]
so what to do now? And what to do if we need to include some other package as well? I mean if not composer update?

**Comment by Haafiz** [comment]
@GrahamCampbell  also composer.lock is still there. Sorry didn't get what you mean by

> Bootstrap CMS contains a composer.lock on purpose so it actually works.

**Comment by Haafiz** [comment]
@GrahamCampbell  I think I should have used composer update <specific package> but how can I correct this? Should I try using `composer install`  after using compser.lock file from the Git repo of this package?

**Comment by GrahamCampbell** [comment]
Yes, only use composer install. The dependencies locked down there have been tested and should work.

**Comment by Haafiz** [comment]
@GrahamCampbell Ok thanks, I am doing so. After that can I do `composer require guzzlehttp/guzzle`  after it is once working? Or I need to include that into composer.json and hit composer update `composer update guzzlehttp/guzzle` ?

**Comment by Haafiz** [comment]
@GrahamCampbell  it didn't completed but now gives this error:

`> php artisan clear-compiled
PHP Fatal error:  Trait 'Illuminate\Auth\Access\HandlesAuthorization' not found in /var/www/html/alphavu/dynamic/bootstrap/cache/compiled.php on line 737
Script php artisan clear-compiled handling the post-install-cmd event returned with an error

                                                                                                                                                       
  [RuntimeException]                                                                                                                                   
  Error Output: PHP Fatal error:  Trait 'Illuminate\Auth\Access\HandlesAuthorization' not found in /var/www/html/alphavu/dynamic/bootstrap/cache/comp  
  iled.php on line 737                                                                                                                                 
                        `

**Comment by GrahamCampbell** [comment]
Delete the contents of the bootstrap/cache folder, then run `php artisan app:update`.

**Comment by Haafiz** [comment]
@GrahamCampbell  Ok done. Thanks a lot , so now I can do `composer require guzzlehttp/guzzle` or now  I need to do `composer update guzzlehttp/guzzle` ? or I again need to `composer install` again? I guess I `composer install` is not required again because error was in `post-install-cmd event`.

**Comment by Haafiz** [comment]
@GrahamCampbell  it seems fine on command line  but after that it is showing same error when I tried in browser: 
```Fatal error: Uncaught ReflectionException: Class log does not exist in /var/www/html/alphavu/dynamic/bootstrap/cache/compiled.php:1291 Stack trace: #0 /var/www/html/alphavu/dynamic/bootstrap/cache/compiled.php(1291): ReflectionClass->__construct('log') #1 /var/www/html/alphavu/dynamic/bootstrap/cache/compiled.php(1242): Illuminate\Container\Container->build('log', Array) #2 /var/www/html/alphavu/dynamic/bootstrap/cache/compiled.php(1780): Illuminate\Container\Container->make('log', Array) #3 /var/www/html/alphavu/dynamic/vendor/graham-campbell/exceptions/src/ExceptionHandler.php(64): Illuminate\Foundation\Application->make('log') #4 [internal function]: GrahamCampbell\Exceptions\ExceptionHandler->__construct(Object(Illuminate\Foundation\Application)) #5 /var/www/html/alphavu/dynamic/bootstrap/cache/compiled.php(1306): ReflectionClass->newInstanceArgs(Array) #6 /var/www/html/alphavu/dynamic/bootstrap/cache/compiled.php(1242): Illuminate\Container\Container->build('GrahamCampbell\\...', Array) #7 /var/www/html/alphavu/dynam in /var/www/html/alphavu/dynamic/bootstrap/cache/compiled.php on line 1291'```

**Comment by GrahamCampbell** [comment]
That error is saying there was an error while trying to log the actual error. Not much help to me.

**Comment by Haafiz** [comment]
@GrahamCampbell  yeah but what to do to fix the error that come at time of logging? And how can I report actual error it is trying to log?

**Comment by Haafiz** [comment]
@GrahamCampbell It is pointing to right file that is LoggerInterface at right place in Exceptions package of yours, then why Log class isn't accessible?

**Comment by GrahamCampbell** [comment]
Because something crashed earlier on before that interface was bound.

**Comment by Haafiz** [comment]
@GrahamCampbell  right but how can I try to debug that? Or should I pull code from server as it seems to be working there?

**Comment by Haafiz** [comment]
@GrahamCampbell  thanks a lot, finally it is working. Problem was that somehow mbstring extension wasn't installed. Not sure how it was previously working without that. I am using PHP7, I guess I didn't mention it in above messages otherwise you could probably tell me about this.

Anyway, thanks  a lot Graham.

**Comment by GrahamCampbell** [comment]
That's odd. Composer shouldn't have allowed the instalo to happen withouthe extension.
