### ISSUE TITLE
Create new Blades

### ISSUE THREAD

**Issue by BenJule** [BootstrapCMS/CMS#222]
If i create a new blade i get an cache error! How can i fix this? I know BootstrapCMS is an CMS but i need to parse a json file :/

Greetz
Ben

**Comment by BenJule** [comment]
Its possible to get support für Bootstrap-table?

**Comment by GrahamCampbell** [comment]
I don't have time to add this myself I'm afrid.

**Comment by BenJule** [comment]
is there a way to load external jsonfile?
