### ISSUE TITLE
Error: Parse error: syntax error

### ISSUE THREAD

**Issue by AhrimanSefid** [BootstrapCMS/CMS#230]
Hi.

`Parse error: syntax error, unexpected '[' in /home/appma/public_html/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php on line 33`

**Comment by GrahamCampbell** [comment]
You need to upgrade your PHP version.

**Comment by AhrimanSefid** [comment]
PHP 5.6.23

**Comment by GrahamCampbell** [comment]
That can't be the one running on the web server. It may be the one in your cli tho.

**Comment by AhrimanSefid** [comment]
litespeed
