### ISSUE TITLE
Can BootstrapCMS work with MongoDB

### ISSUE THREAD

**Issue by stonevo** [BootstrapCMS/CMS#233]
Hi,
I randomly saw BootstrapCMS by google searching and fascinating with it. BootstrapCMS worked fine with MySQL but i usually work with MongoDB rather than MySQL and i tried to change MongoDB but no luck. I already installed Laravel MongoDB (https://github.com/jenssegers/laravel-mongodb) but i got this error : 
**Argument 2 passed to Illuminate\Database\Query\Builder::__construct() must be an instance of Illuminate\Database\Query\Grammars\Grammar, null given, called in /projectPath/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php on line 1874 and defined**
So i dont know is it the right place for asking or not. I'm sorry

**Comment by GrahamCampbell** [comment]
No, it doesn't work with mongo.

**Comment by stonevo** [comment]
Ok thanks @GrahamCampbell for information.
