### ISSUE TITLE
How to order with paginate

### ISSUE THREAD

**Issue by mingxing** [BootstrapCMS/CMS#235]
Hi

I am using $products = ProductRepository::paginate();

But how to order with sort/sortBy?

I checked the function of public function paginate(), it seems just read the order and sort in Model:

if (property_exists($model, 'order')) {
            $paginator = $model::orderBy($model::$order, $model::$sort)->paginate($model::$paginate, $model::$index);
} else {
            $paginator = $model::paginate($model::$paginate, $model::$index);
 }

**Comment by GrahamCampbell** [comment]
Sorry, our issue tracker is for bugs in the CMS. Try the Laravel forums or something. :)
