### ISSUE TITLE
cf6824c8-8ffc-418c-a07a-315830a12e19. -- Giving this Error Please Help

### ISSUE THREAD

**Issue by Sidbaba** [BootstrapCMS/CMS#236]
I have configured everything but when i run it it is giving 500 internal error

**Comment by GrahamCampbell** [comment]
That error code is unique to you. It allows you to look up the error in your log file.

**Comment by GrahamCampbell** [comment]
When the error page says contact support or whatever, that's aimed at your users to contact you.

**Comment by JoseCage** [comment]
@Sidbaba can you share the log or more information about the error? Maybe i can help you.
