### ISSUE TITLE
Error 500

### ISSUE THREAD

**Issue by AhrimanSefid** [BootstrapCMS/CMS#237]
Hi All.
Me install BootstrapCMS but not run send me error :
> 
Error 500
Houston, We Have A Problem.
Internal Server Error
What does this mean?

Something went wrong on our servers while we were processing your request. An error has occurred and this resource cannot be displayed. This occurrence has been logged, and a highly trained team of monkeys has been dispatched to deal with your problem. We're really sorry about this, and will work hard to get this resolved as soon as possible.

This error can be identified by e7e70a36-dd6a-4419-bd40-901ef17434d4. You might want to take a note of this code.

Perhaps you would like to go to our home page?

My Site:
http://blogall.ir/public/pages/home

**Comment by AhrimanSefid** [comment]
Fixed Error 500.
but not load css.

**Comment by GrahamCampbell** [comment]
Looks like you've not compiled the assets using gulp.

**Comment by GrahamCampbell** [comment]
Please follow everything in https://github.com/BootstrapCMS/CMS#installation.

**Comment by AhrimanSefid** [comment]
yes ty.
install work.
thanks a lot.
